---
name: "Example Add-on"
description: "Ein Beispiel-Add-on als Vorlage f√ºr eigene Entwicklungen"
version: "0.0.2"
slug: "example-addon"
image: "ghcr.io/helix-git/{arch}-example-addon"
init: false
arch:
  - aarch64
  - amd64
ingress: true
ingress_entry: /
homeassistant_config: true
auth_api: true
