---
name: "Example Add-on"
description: "Ein Beispiel-Add-on als Vorlage f√ºr eigene Entwicklungen"
# x-release-please-start-version
version: "0.1.0"
# x-release-please-end
slug: "example-addon"
image: "ghcr.io/helix-git/ha-example-addon/{arch}"
init: false
arch:
  - aarch64
  - amd64
ingress: true
ingress_entry: /
homeassistant_config: true
auth_api: true
